server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/youco/Desktop/streaming-platform/config-repo
          default-label: main
management:
  endpoints:
    web:
      exposure:
        include: "*"
